AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend for the AWS Community Day networking app

Parameters:
  ShortIdGSIName:
    Type: String
    Default: ShortIdGSI
    Description: Name of the Short ID Global Secondary Index
  InvertedGSIName:
    Type: String
    Default: InvertedGSI
    Description: Name of the Inverted Global Secondary Index
Globals:
  Function:
    CodeUri: function
    Timeout: 5
    MemorySize: 128
    Runtime: python3.12

    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: PowertoolsCommunityDay
        POWERTOOLS_METRICS_NAMESPACE: Powertools
        LOG_LEVEL: INFO
        DYANMODB_TABLE_NAME: !Ref DynamoDBTable
    Tags:
      LambdaPowertools: python
  Api:
    TracingEnabled: true
Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${AWS::StackName}-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: short_id
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Ref ShortIdGSIName
          KeySchema:
            - AttributeName: short_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: !Ref InvertedGSIName
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref 'AWS::StackName'
  CountLegitimateScans:
    # SQS
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-count-legitimate-scans'
      Tags:
        - Key: Environment
          Value: !Ref 'AWS::StackName'

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update_fields.lambda_handler
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            Path: /attendee
            Method: POST
      Environment:
        Variables:
          INDEX_NAME: !Ref ShortIdGSIName
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
  GetInformationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_information.lambda_handler
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        GetInformationEvent:
          Type: Api
          Properties:
            Path: /attendee
            Method: GET
      Environment:
        Variables:
          INDEX_NAME: !Ref ShortIdGSIName
          QUEUE_URL: !Ref CountLegitimateScans
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref CountLegitimateScans
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDBTable

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
